// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7NYdvkz0-mHJDggZ5YZ3yORc1Jl07T_U',
    appId: '1:124374770168:web:cec0506b380c4e2c26760d',
    messagingSenderId: '124374770168',
    projectId: 'medifindyapp',
    authDomain: 'medifindyapp.firebaseapp.com',
    storageBucket: 'medifindyapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi3cWUgmHWca4RRcJy1EgR9-9pLyRhxgA',
    appId: '1:124374770168:android:62c00f3f4b536e7a26760d',
    messagingSenderId: '124374770168',
    projectId: 'medifindyapp',
    storageBucket: 'medifindyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe1771vSyxuCWEUHuHzuD30gE4rCTQhXs',
    appId: '1:124374770168:ios:2a208ce08e864f0626760d',
    messagingSenderId: '124374770168',
    projectId: 'medifindyapp',
    storageBucket: 'medifindyapp.appspot.com',
    iosBundleId: 'com.example.pharmacyAppnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe1771vSyxuCWEUHuHzuD30gE4rCTQhXs',
    appId: '1:124374770168:ios:72094aac15b70a9626760d',
    messagingSenderId: '124374770168',
    projectId: 'medifindyapp',
    storageBucket: 'medifindyapp.appspot.com',
    iosBundleId: 'com.example.pharmacyAppnew.RunnerTests',
  );
}
